// import Head from "next/head";
// import Header from "@/components/Hero/Header";
// import Footer from "@/components/Footer";
// import ServicesSection from "@/components/services/Services";

// export default function Services() {
//   return (
//     <>
//       <Head>
//         <title>Tarot</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/img/WithBG.png" />
//       </Head>
//       <Header />
//       <main>
//         <ServicesSection />
//         <Footer />
//       </main>
//     </>
//   );
// }
